### ISSUE TITLE
 laminar中margin trading首页可以显示My Positions / Orders交易记录，但是进入具体交易对页面My Positions / Orders Open显示没有数据

### ISSUE THREAD

**Issue by frighter518** [laminar-protocol/flow-exchange#23]
laminar中margin trading首页可以显示My Positions / Orders交易记录，但是进入具体交易对页面My Positions / Orders Open显示没有数据。下级页面我一点，进的是https://flow.laminar.one/margin/0/EURUSD这个页面，看不到交易数据。
5CccLc64WB2hwWorqg92A4S5y9fwAiAdbAKLRY5obDskA26N

**Comment by xlc** [comment]
有laminar和fx两个池子，你的交易在fx的池子里面，不在laminar里面。
