### ISSUE TITLE
Acala 糖果节活动8月3日开启交易大赛,水龙头发放的测试币只可领取一次 2000 枚 aUSD 与 2 枚 ACA，但laminar的水龙头怎么还能领取aUSD？

### ISSUE THREAD

**Issue by frighter518** [laminar-protocol/flow-exchange#24]
Acala 糖果节活动8月3日开启交易大赛,platform水龙头发放的测试币只可领取一次 2000 枚 aUSD 与 2 枚 ACA，但laminar的水龙头怎么还能领取aUSD？有人知道从laminar的水龙头还可以领aUSD，有人不知道还可以领，这个大赛还公平吗？
5CccLc64WB2hwWorqg92A4S5y9fwAiAdbAKLRY5obDskA26N

**Comment by xlc** [comment]
Laminar水龙头应该早就不能领了。
而且所有转账（包括水龙头）的钱都会计入本金，最好是按照收益率来算拍卖，所以本金多少是无所谓的。
